In [1]:
#numpy  is defined as numerical python.
#it is a powerful library which is used for numerical computataions.
#it is 50 times faster than python lists.


In [3]:
#array() is used to print array
#type function is used to get the type of the array.

In [4]:
#one dimensional array
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
#2 dimensional array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
#3 dimensional array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
#2dimensional
import numpy as np
arr=np.zeros((2,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
#initiialise numpy with ones
import numpy as np
arr=np.ones([3])
arr

array([1., 1., 1.])

In [10]:
#int type
import numpy as np
arr=np.ones([2,4],dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
#k=0 → main diagonal
#k=1 → diagonal just above the main diagonal
#k=-1 → diagonal just below the main diagonal
import numpy as np
arr=np.eye(3,4,k=1)
arr

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
import numpy as np
arr=np.eye(3,4,k=-2)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [13]:
#initialise numpy with full
import numpy as np
arr=np.full(5,5)
arr

array([5, 5, 5, 5, 5])

In [14]:
#2-d
import numpy as np
arr=np.full((3,4),7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
import numpy as np
arr=np.full([2,3],1)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [120]:
#float values
import numpy as np
arr=np.full([2,3],1.21)
arr

array([[1.21, 1.21, 1.21],
       [1.21, 1.21, 1.21]])

In [9]:
import numpy as np
arr=np.eye(4,4,k=0)
c=arr.reshape(2,4,2)
c

array([[[1., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.]]])

In [11]:
#arange in numpy
import numpy as np
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [15]:
import numpy as np
arr=np.arange(1,5,0.2)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [21]:
import numpy as np
arr=np.arange(1,25,1.5,dtype=int)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [64]:
#random.randint in numpy
import numpy as np
np.random.seed(1)
arr=np.random.randint(10)
arr

5

In [66]:
import numpy as np
arr=np.random.randint(10)
arr

8

In [72]:
import numpy as np
arr=np.random.randint(5,16)
arr

5

In [96]:
import numpy as np

arr=np.random.randint(1,7,size=2)
arr

array([1, 6])

In [102]:
import numpy as np

arr=np.random.randint(1,7,size=(2,4))
arr

array([[1, 1, 6, 4],
       [3, 2, 1, 4]])

In [109]:
import numpy as np
arr=np.random.randint(0,100,size=5,dtype=int)
arr

array([52, 80, 41, 82, 15])

In [111]:
#shape in numpy
import numpy as np
arr=np.array([1,2,3,4,5])
arr.shape

(5,)

In [113]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [115]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr.shape

(2, 2, 3)

In [125]:
arr=np.arange(6)
arr.shape
arr=arr.reshape((2,3))
arr


array([[0, 1, 2],
       [3, 4, 5]])

In [137]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
result=np.vstack((a,b))
result

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [139]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
result=np.hstack((a,b))
result

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [147]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
result=np.column_stack((a,b))
result

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7],
       [5, 8]])

In [153]:
import numpy as np #returns common vales
n1=np.array([1,2,3])
n2=np.array([1,3,4,])
np.intersect1d(n1,n2)

array([1, 3])

In [157]:
#remove common values and returns n1
import numpy as np
n1=np.array([1,2,3])
n2=np.array([1,3,4,])
np.setdiff1d(n1,n2)

array([2])

In [159]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([1,3,4,])
np.setdiff1d(n2,n1)

array([4])

In [161]:
#addition in numpy
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])
np.sum((n1,n2))

32

In [19]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
np.fromiter(a,dtype=int,count=3)

array([1, 2, 3])

In [27]:
a=np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
a=np.zeros([2,4,3])
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
np.zeros([5,6,7])

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
    

In [43]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.ones(2)

array([1., 1.])

In [47]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
np.full([2,3],7)

array([[7, 7, 7],
       [7, 7, 7]])

In [51]:
np.full([2,3,4],9)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [53]:
np.full([2,3],0)

array([[0, 0, 0],
       [0, 0, 0]])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.random.randint(2,3)

2

In [73]:
np.random.rand(2,3,3)

array([[[0.23081366, 0.79805138, 0.69450403],
        [0.60913728, 0.71484112, 0.43718265],
        [0.05195972, 0.57805236, 0.19056114]],

       [[0.44862467, 0.39493699, 0.15197942],
        [0.65845913, 0.80153884, 0.03404941],
        [0.94778192, 0.6698432 , 0.35501371]]])

In [81]:
b=np.arange(2,9)
print(b)

[2 3 4 5 6 7 8]


In [83]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [99]:
np.arange(0,100,5,dtype=float)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

In [91]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [97]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [101]:
np.linspace(1,1.9,5)

array([1.   , 1.225, 1.45 , 1.675, 1.9  ])

In [116]:
np.linspace(1,100,10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [118]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [120]:
np.logspace(1,100,10,endpoint=False)

array([1.00000000e+01, 7.94328235e+10, 6.30957344e+20, 5.01187234e+30,
       3.98107171e+40, 3.16227766e+50, 2.51188643e+60, 1.99526231e+70,
       1.58489319e+80, 1.25892541e+90])

In [126]:
np.logspace(1,20,20,base=3)

array([3.00000000e+00, 9.00000000e+00, 2.70000000e+01, 8.10000000e+01,
       2.43000000e+02, 7.29000000e+02, 2.18700000e+03, 6.56100000e+03,
       1.96830000e+04, 5.90490000e+04, 1.77147000e+05, 5.31441000e+05,
       1.59432300e+06, 4.78296900e+06, 1.43489070e+07, 4.30467210e+07,
       1.29140163e+08, 3.87420489e+08, 1.16226147e+09, 3.48678440e+09])

In [130]:
a=np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [132]:
a.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [134]:
np.size(a)

9

In [138]:
a.dtype

dtype('int32')

In [146]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
a[0][2]


3

In [150]:
a[0]

array([1, 2, 3])

In [158]:
s=np.arange(10,100,10)
s

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [161]:
s[2:5]

array([30, 40, 50])

In [165]:
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [169]:
b=np.copy(a)
b

array([[10, 20, 30],
       [40, 50, 60]])

In [177]:
c=b.view()
c

array([[10, 20, 30],
       [40, 50, 60]])

In [179]:
a=np.array([30,40,50,10,60])
a

array([30, 40, 50, 10, 60])

In [181]:
np.sort(a)

array([10, 30, 40, 50, 60])

In [187]:
s=np.array([[3,2,4],[9,7,0]])
s

array([[3, 2, 4],
       [9, 7, 0]])

In [195]:
np.sort(s)


array([[2, 3, 4],
       [0, 7, 9]])

In [197]:
np.sort(s,axis=1)

array([[2, 3, 4],
       [0, 7, 9]])

In [199]:
np.sort(s,axis=0)##

array([[3, 2, 0],
       [9, 7, 4]])

In [201]:
a=np.array([10,20,30])
b=np.array([50,60,70])
np.append(a,b)

array([10, 20, 30, 50, 60, 70])

In [207]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.append(a,b,axis=0)

array([[10, 20, 30],
       [11, 12, 13],
       [50, 60, 70],
       [19, 10, 14]])

In [209]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.append(a,b,axis=1)

array([[10, 20, 30, 50, 60, 70],
       [11, 12, 13, 19, 10, 14]])

In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
np.insert(a,4,6)

array([1, 2, 3, 4, 6, 5])

In [9]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.insert(a,(3),100)

array([  1,   2,   3, 100,   4,   5,   6,   7,   8,   9,  10])

In [29]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [37]:
np.delete(a,0)

array([2, 3, 4])

In [41]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.concatenate((a,b))

array([[10, 20, 30],
       [11, 12, 13],
       [50, 60, 70],
       [19, 10, 14]])

In [47]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.concatenate((a,b),axis=1)

array([[10, 20, 30, 50, 60, 70],
       [11, 12, 13, 19, 10, 14]])

In [51]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
print(np.stack((a,b)))

[[[10 20 30]
  [11 12 13]]

 [[50 60 70]
  [19 10 14]]]


In [61]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.vstack((a,b))

array([[10, 20, 30],
       [11, 12, 13],
       [50, 60, 70],
       [19, 10, 14]])

In [55]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.hstack((a,b))

array([[10, 20, 30, 50, 60, 70],
       [11, 12, 13, 19, 10, 14]])

In [63]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.dstack((a,b))

array([[[10, 50],
        [20, 60],
        [30, 70]],

       [[11, 19],
        [12, 10],
        [13, 14]]])

In [77]:
x=np.arange(10,110,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [79]:
np.split(x,5)

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

s1,s2,s3,s4,s5=np.split(x,5)
s1,s2,s3,s4,s4

In [86]:
s1,s2,s3,s4,s5=np.split(x,5) 
s1,s2,s3,s4,s4

(array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([70, 80]))

In [88]:
x=np.arange(10,130,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [90]:
np.split(x, (4,3))

[array([10, 20, 30, 40]),
 array([], dtype=int32),
 array([ 40,  50,  60,  70,  80,  90, 100, 110, 120])]

In [98]:
a=np.arange(10,130,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [100]:
np.where(a==80)

(array([7], dtype=int64),)

In [103]:
a=np.array([10,20,30,40,50])
np.searchsorted(a,20)

1

In [105]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.add(a,b)

array([[ 60,  80, 100],
       [ 30,  22,  27]])

In [121]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.subtract(a,b)

array([[-40, -40, -40],
       [ -8,   2,  -1]])

In [119]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.multiply(a,b)

array([[ 500, 1200, 2100],
       [ 209,  120,  182]])

In [125]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.divide(a,b)

array([[0.2       , 0.33333333, 0.42857143],
       [0.57894737, 1.2       , 0.92857143]])

In [133]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[50,60,70],[19,10,14]])
np.sqrt(a)
np.sqrt(b)

array([[7.07106781, 7.74596669, 8.36660027],
       [4.35889894, 3.16227766, 3.74165739]])

In [135]:
a=np.array([[10,20,30],[11,12,13]])
np.min(a)

10

In [137]:
a=np.array([[10,20,30],[11,12,13]])
np.max(a)

30

In [139]:
a=np.array([[10,20,30],[11,12,13]])
np.max(a,axis=0)

array([11, 20, 30])

In [141]:
np.mean(a)

16.0

In [143]:
np.median(a)

12.5

In [147]:
np.std(a)

7.047458170621991

In [149]:
np.var(a)

49.666666666666664