In [1]:
#numpy:numpy(numerical python) is a powerful library which is used for numerical computing in python. it supports multi dimensional array  and matrices along with mathematical functions 
!pip install numpy

In [2]:
import numpy as np

In [3]:
#creating numpy
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
#creating multi dimensional array
b=np.array([[1,2,3],[4,5,6]],ndmin=1)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#array attributes
c=np.array([[1,2,3],[4,5,6]])
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

(2, 3)
2
6
int32


In [11]:
#special arrays
c=np.array([[1,2,3],[4,5,6]])
np.zeros((2,3))
 


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [21]:
#range and linspace
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [17]:
np.linspace(0,100,5).astype(int)

array([  0,  25,  50,  75, 100])

In [19]:
np.linspace(0,30,10).astype(int)

array([ 0,  3,  6, 10, 13, 16, 20, 23, 26, 30])

In [29]:
c.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
#indexing and slicing
a=np.array([10,20,30,40])
print(a[1])

20


In [33]:
print(a[1:3])

[20 30]


In [23]:
#Array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a + b)
print(zip(a,b))

[5 7 9]


In [25]:
a=np.array([[1],[2],[3]])
b=np.array([4,5,6])
print(a+b)
print(a-b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]


In [39]:
lst=[2,3,5,7,11]
for i in lst:
    if i%2==0:
        print( i,"it is even")
    if i%2!=0:
        print(i,"it is an dd")
        

2 it is even
3 it is an dd
5 it is an dd
7 it is an dd
11 it is an dd


In [47]:
import numpy as np
print(np.__version__)


1.26.4


In [49]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [31]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [53]:
#o-dimensional array
import numpy as np

arr = np.array(42)

print(arr)


42


In [55]:
#1=Dimensional array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [57]:
#2-Dimensional array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [61]:
#3-dimensional array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [63]:
#checking dimensinals
import numpy as np
a=np.array([44])
b=np.array([2,3,4,6])
c=np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
1
2
3


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [71]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [75]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [81]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr[1,0,2])

3


In [79]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) # depth,row,column

6


In [89]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [93]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [96]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [98]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [104]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::5])

[1 6]


In [106]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [11]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [87]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#newarr=np.sum(arr)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
import numpy as np
arr=np.arange(1,23)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [39]:
arr=np.arange(1,25,3)
print(arr)

[ 1  4  7 10 13 16 19 22]


In [53]:
arr=np.arange(1,11).reshape(5,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [55]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
arr=np.ones([2,3])
arr


array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
arr=np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
arr=np.empty([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
arr=np.random.random([2,3])
arr

array([[0.52831369, 0.65170243, 0.42310516],
       [0.46521027, 0.77446082, 0.94316958]])

In [67]:
arr=np.linspace(-10,10,10)
arr

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [75]:
arr=np.linspace(100,10)
arr

array([100.        ,  98.16326531,  96.32653061,  94.48979592,
        92.65306122,  90.81632653,  88.97959184,  87.14285714,
        85.30612245,  83.46938776,  81.63265306,  79.79591837,
        77.95918367,  76.12244898,  74.28571429,  72.44897959,
        70.6122449 ,  68.7755102 ,  66.93877551,  65.10204082,
        63.26530612,  61.42857143,  59.59183673,  57.75510204,
        55.91836735,  54.08163265,  52.24489796,  50.40816327,
        48.57142857,  46.73469388,  44.89795918,  43.06122449,
        41.2244898 ,  39.3877551 ,  37.55102041,  35.71428571,
        33.87755102,  32.04081633,  30.20408163,  28.36734694,
        26.53061224,  24.69387755,  22.85714286,  21.02040816,
        19.18367347,  17.34693878,  15.51020408,  13.67346939,
        11.83673469,  10.        ])

In [77]:
arr=np.linspace(-2,12,6)
arr

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [79]:
arr=np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
arr=np.identity(6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [91]:
arr=np.arange(12,dtype=float).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [99]:
arr=np.arange(8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

arr.ndim
arr

In [103]:
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [105]:
a1.itemsize

4

In [123]:
x=np.linspace(0,10,5, endpoint=False)
x

array([0., 2., 4., 6., 8.])

In [135]:
x=np.array([33,22,2.5]) 
x

array([33. , 22. ,  2.5])

In [137]:
z2=np.arange(12,24).reshape(3,4)
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
z2+2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [155]:
a=np.array([[[1,2,3,4]]])
print(np.linalg.matrix_rank(a))

2


In [192]:
import numpy as np
np.random.seed(11)
arr=np.random.randint(1,10,5)
print(arr)

[1 2 8 2 8]


In [225]:
z1=np.array([1,2,3,4,5])
z2=np.array([4,5,6,7,8])
z= z1+z2
z

array([ 5,  7,  9, 11, 13])

In [241]:
k1=np.random.random((3,3)) 
k1= np.round(k1*100)
k1

array([[32., 11.,  8.],
       [71., 60.,  6.],
       [48., 40., 85.]])

In [243]:
np.max(k1)


85.0

In [245]:
np.min(k1)

6.0

In [247]:
np.sum(k1)

361.0

In [251]:
np.prod(k1)

11746639872000.0

In [259]:
np.max(k1,axis=1)

array([32., 71., 85.])

In [265]:
np.max(k1,axis=1)

array([32., 71., 85.])

In [269]:
arr=np.array([[[0, 1],
 [2, 3]],
 [[2, 5],
 [6, 7]]])
arr

array([[[0, 1],
        [2, 3]],

       [[2, 5],
        [6, 7]]])

In [283]:
import numpy as np

arr = np.array([
    [
        [0, 1],
        [2, 3]
    ],
    [
        [2, 5],
        [6, 7]
    ]
])

# Find the indices of the value 2
indices = np.where(arr == 5)

# Combine the indices into a list of tuples
locations = list(zip(*indices))

print(locations)
#indices

[(1, 0, 1)]


In [287]:
arr=np.array([
    [
        [1,2,3,4]
    ]
             ])
indices=np.where(arr==2)
indices

(array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))