In [1]:
for i in range(2,20,2):
    print(i,end=" ")

2 4 6 8 10 12 14 16 18 

In [3]:
a="malayalam"
if a==a[::-1]:
    print("it is a palindrome")
else:
    print("it is not a palindrome")


it is a palindrome


In [5]:
a=int(input("enter a number:"))
if a>0:
    print("it is a positive number")
if a<0:
    print("it is a negetive number")
if a==0:
      print("it is a zero")
      

enter a number: 3


it is a positive number


In [7]:
a=" "
if len(a)==0:
    print("string is empty")
if len(a)!=0:
    print("string is not empty")

string is not empty


In [9]:
a=int(input("enter a number:"))
if a%3==0 and a%5==0:
    print("given number is divisible by 3 and 5")
if a%3!=0 and a%5!=0:
    print("given number is not divisible by 3 and 5")

enter a number: 15


given number is divisible by 3 and 5


In [19]:
num= int(input("enter a number:"))
factorial=1
for i in range(1,num+1):
    factorial=factorial*i
print(factorial)

enter a number: 5


120


In [21]:
list=["apple","banana","orange","graphes"]
for i in list:
    print(i)

apple
banana
orange
graphes


In [25]:
list=[24,3,25,47,13]
max_value=list[0]
for i in list:
    if i>max_value:
        max_value=i
print(max_value)

47


In [27]:
str="hello"
for char in str:
    print(char)

h
e
l
l
o


In [25]:
string="helloworld"
vowels="aeiouAEIOU"
count=0
for i in string:
    if i in vowels:
        count+=1
print(count)

3


In [21]:
dict={"name": "Alice","age": 30,"city": "New York"
}
for k,v in dict.items():
    print(f"{k}:{v}")

name:Alice
age:30
city:New York


In [25]:
for  i in range(1,6):
    for j in range(i):
        print("*",end=" ")
    print()
    

    
    
    

* 
* * 
* * * 
* * * * 
* * * * * 


In [27]:
a,b=0,1
for i in range(15):
    print(a)
    a,b=b,a+b

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377


In [33]:

sum=0
for i in range(1,101):
    if i%2==0:
        sum = sum+i
print(sum)

2550


In [39]:
a=[1,2,3,6,8,5]
b=[19,18,17,5,3]
for i in a:
    if i in b:
        print(i)

3
5


In [5]:
num=int(input("enter a number:"))
if num<=1:
    print("it is not aprime number")
else:
    for i in range(2,num):
        if num%i==0:
            print("it is not a prime number")
            break
    else:
        print("it is a prime number")
        

enter a number: 2


it is a prime number


In [41]:
for i in range(1,11):
    for j in range(1,6):
        print(f"{i}*{j}={i*j}",end="\t")
    print()

1*1=1	1*2=2	1*3=3	1*4=4	1*5=5	
2*1=2	2*2=4	2*3=6	2*4=8	2*5=10	
3*1=3	3*2=6	3*3=9	3*4=12	3*5=15	
4*1=4	4*2=8	4*3=12	4*4=16	4*5=20	
5*1=5	5*2=10	5*3=15	5*4=20	5*5=25	
6*1=6	6*2=12	6*3=18	6*4=24	6*5=30	
7*1=7	7*2=14	7*3=21	7*4=28	7*5=35	
8*1=8	8*2=16	8*3=24	8*4=32	8*5=40	
9*1=9	9*2=18	9*3=27	9*4=36	9*5=45	
10*1=10	10*2=20	10*3=30	10*4=40	10*5=50	


In [60]:
num=int(input("enter a number:"))
factorial=1
for i in range(1,num+1):
    factorial*=i
print("factorial:",factorial)

enter a number: 5


factorial: 120


In [62]:
a="pavan"
for i in a[::-1]:
    print(i,end=" ")

n a v a p 

In [64]:
squares=[]
for i in range(1,11):
    squares.append(i**2)
print(squares)

    
    
    

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [70]:
sentence="this is pavan"
count=1
for i in sentence:
    if i==' ':
        count+=1
print(count)

3


In [80]:
num=int(input("enter a number:"))
count=0
for digit in str(num):
    if digit.isdigit():
        count+=int(digit)
print(count)

enter a number: 234


TypeError: 'str' object is not callable

In [84]:
base=int(input("enter base value"))
exponent=int(input("enter exponent value"))
result=1
for _ in range(exponent):
    result=result*base
print(result)

enter base value 2
enter exponent value 3


8


In [86]:
a=[1,2,3,4,5,6]
for i in a[::-1]:
    print(i,end=" ")

6 5 4 3 2 1 

In [88]:
list=[1,12,15,11,3,0,66]
max_value=list[0]
for i in list:
    if max_value<i:
        max_value=i
print(max_value)
        

66


In [90]:
#functions in python
def name():
    print("hello")
name()
print("this is outer block")

hello
this is outer block


In [53]:
def greet(num):
    print("hello",num)
greet("john")
greet("david")
greet("ramu")

hello john
hello david
hello ramu


In [92]:
def add(a,b):
    sum=a+b
    print("sum is",sum)
add(6,3)
add(13,15)
add(11,12)

sum is 9
sum is 28
sum is 23


In [94]:
def find_square(num):
    result=num*num
    return result
print(find_square(3))

9


In [96]:
def future_function():
    print("pavan")
    pass
    

# this will execute without any action or error
future_function()  

pavan


In [98]:
import math
square_root=math.sqrt(2)
print("square root:",square_root)


square root: 1.4142135623730951


In [100]:
def add_numbers(a=2,b=4):
    sum=a+b
    print("sum:",sum)
add_numbers()
add_numbers(3,5)
add_numbers(3,7)
    
 

sum: 6
sum: 8
sum: 10


In [102]:
def display(firstname,secondname):
    print("firstname:",firstname)
    print("secondname",secondname)
display('pavan','chennamsetty')

firstname: pavan
secondname chennamsetty


#### Define functions for each operation
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Error: Cannot divide by zero."
    return x / y

# Main calculator function
def calculator():
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    choice = input("Enter choice (1/2/3/4): ")

    if choice in ['1', '2', '3', '4']:
        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input. Please enter numeric values.")
            return

        if choice == '1':
            print("Result:", add(num1, num2))
        elif choice == '2':
            print("Result:", subtract(num1, num2))
        elif choice == '3':
            print("Result:", multiply(num1, num2))
        elif choice == '4':
            print("Result:", divide(num1, num2))
    else:
        print("Invalid choice")

# Run the calculator
calculator()


In [110]:
a=int(input("enter a number:"))
sum=0
for i in a:
    sum=sum+int(i)
print(sum)
    
    

enter a number: 123


TypeError: 'int' object is not iterable

In [112]:
a=input("enter a word:")
if a==a[::-1]:
    print("it is a palindrome")
else:
    print("it is not a palindrome")

enter a word: kisik


it is a palindrome


In [114]:
print([i for i in range(1,11) if i%2==0])


[2, 4, 6, 8, 10]


In [116]:
i=int(input("enter a number:"))
print("divisible by 3 and 5"if i%3==0 and i%5==0 else "not divisble by 3 and 5")   

enter a number: 5


not divisble by 3 and 5


In [ ]:
'''def calculator():
    while True:
        print(eval(input()))
calculator()
break'''


In [130]:
print([i for i in range(1,101) if i%2==0 ])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [45]:
print('---'.join("pavan"))

p---a---v---a---n


In [49]:
a,b=0,1
print("fibanacci series:")
for i in range(10):
    print(a)
    
    a,b=b,a+b
     

fibanacci series:
0
1
1
2
3
5
8
13
21
34


In [134]:
a="pavan"
for i in a[::-1]:
    print(i,end=" ")

n a v a p 

In [5]:
a=int(input("enter age:"))
if a>=18:
    print("person is eligible for vote")
else:
    print("person is not eligible for not")

enter age: 23


person is eligible for vote


In [138]:
list1=[10,"Python"]  
list2= [35]
list3=list1+list2  
print (list3)

[10, 'Python', 35]


In [140]:
list1=[100,'python',50.8,'a',[200,300]] 
for lst1 in list1:
    print(lst1)

100
python
50.8
a
[200, 300]


In [154]:
list1=[100,'python',50.8,'a',200]  

list1.insert(5,1500.50)
print(list1)


[100, 'python', 50.8, 'a', 200, 1500.5]


In [156]:
list1.insert(2,None)
print (list1)

[100, 'python', None, 50.8, 'a', 200, 1500.5]


In [158]:
list1.insert(100,'True')
print (list1)

[100, 'python', None, 50.8, 'a', 200, 1500.5, 'True']


In [160]:
def max_two(x,y):
    if x>y:
        return x
    return y
max_two(-1,6)

6

In [16]:
def max_of_three(x,y,z):
    return max_two(x,max_two(y,z))
print(max_of_three(5,8,-4))

NameError: name 'max_two' is not defined

In [22]:
def max_of_three(x, y, z):
    # Call max_of_two function to find the maximum of y and z,
    # then compare it with x to find the overall maximum
    return max_of_two(x, max_of_two(y, z))

# Print the result of calling max_of_three function with arguments 3, 6, and -5
print(max_of_three(3, 6, -5)) 


NameError: name 'max_of_two' is not defined

In [162]:
def max_of_two(x, y):
    # Check if x is greater than y
    if x > y:
        # If x is greater, return x
        return x
    # If y is greater or equal to x, return y
    return y

# Define a function that returns the maximum of three numbers
def max_of_three(x, y, z):
    # Call max_of_two function to find the maximum of y and z,
    # then compare it with x to find the overall maximum
    return max_of_two(x, max_of_two(y, z))

# Print the result of calling max_of_three function with arguments 3, 6, and -5
print(max_of_three(3, 6, -5))

6


In [54]:
def sum(numbers):
    total=0
    for x in numbers:
        total=total+x
    return total
sum((3,3,4,4,5,5))

24

In [164]:
a,b=0,1
print("fibinacci series:")
for i in range(10):
     
    print(a)
    a,b=b,a+b



fibinacci series:
0
1
1
2
3
5
8
13
21
34


In [168]:
def max_of_three(a,b,c):
    if a>=b and a>=c:
        return a
    elif b>=a and b>=c:
        return b
    else:
        return c
num1=int(input("enter a number1:"))
num2=int(input("enter a number2:"))
num3=int(input("enter a number3:"))

print(max_of_three(num1,num2,num3))


enter a number1: 2
enter a number2: 3
enter a number3: 1


3


In [170]:
def multiply(numbers):
    total=1
    for i in numbers:
        total=total*i
    return total
num1=int(input("enter a num1:"))
num2=int(input("enter a num2:"))
num3=int(input("enter a num3:"))
multiply((num1,num2,num3))

enter a num1: 2
enter a num2: 1
enter a num3: 3


6

In [172]:
def multiply(numbers):
    total=1
    for i in numbers:
        total=total*i
    return total
multiply((1,2,3,4,4))

96

In [176]:
def reverse():
    a="pavan"
    b="narendra"
    print(a[::-1])
    print(b[::-1])
reverse()


navap
ardneran


In [149]:
def fact(num):
    fact=1
    for i in range(1,num+1):
        fact=fact*i
    print("factorial:",fact)
fact(5)
fact(4)
fact(7)

factorial: 120
factorial: 24
factorial: 5040


In [178]:
#count the number of upper and lower  casees in a string
def string_test(s):
    d={"UPPERCASE":0,"LOWERCASE":0}
    for c in s:
        if c.isupper():
            d["UPPERCASE"]+=1
        elif c.islower():
            d["LOWERCASE"]+=1
        else:
            pass
    print("original string",s)
    print("number of upper casese:",d["UPPERCASE"])
    print("number of lower cases:",d["LOWERCASE"])
string_test('Pnddn And Voice And None')

original string Pnddn And Voice And None
number of upper casese: 5
number of lower cases: 15


In [180]:
def unique_list(l):
    x=[]
    for a in l:
        if a not in x:
            x.append(a)
    return x
print(unique_list([1,2,2,2,3,6,6,7,4,9]))

[1, 2, 3, 6, 7, 4, 9]


In [182]:
def test_prime(n):
    if n==1:
        return False
    elif n==2:
        return True
    else:
        for x in range(2,n):
            if n%x==0:
                return False
        return True
print(test_prime(9))
                

False


In [184]:
a="MALAYALAM"
if a==a[::-1]:
    print("palindrome")
else:
    print("not a palindrome")

palindrome


In [5]:
n=5
for i in range(n):
    for j in range(n):
        if i==0 or i==n-1 or j==0 or j==n-1 or i==j or i+j==n-1:
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()
    
    
 

* * * * * 
* *   * * 
*   *   * 
* *   * * 
* * * * * 


In [194]:
n = 7  # You can change the size as needed

for i in range(n):
    for j in range(n):
        # Print * on the border or the two diagonals (forming the cross)
        if i == 0 or i == n - 1 or j == 0 or j == n - 1 or i==j or i+j==n-1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()


* * * * * * * 
* *       * * 
*   *   *   * 
*     *     * 
*   *   *   * 
* *       * * 
* * * * * * * 


In [9]:
string="pavan is a singer"
vowels="AEIOUaeiou"
count=0
for i in string:
    if i in vowels:
        count= count+1
print(count)
    

6


In [1]:
a="Hello world"
print(a[::-1])


dlrow olleH


In [49]:
def string():
    a="madam"
    if a==a[::-1]:
        print("it is a palindrome")
    
string()
    

it is a palindrome


In [3]:
 def remove_duplicates(input_list):
    unique_list = []
    for item in input_list:
        if item not in unique_list:
            unique_list.append(item)
    return unique_list

# Example usage
original_list = [1, 2, 2, 3, 4, 4, 5, 1]
result = remove_duplicates(original_list)
print("Original list:", original_list)
print("List without duplicates:", result)


Original list: [1, 2, 2, 3, 4, 4, 5, 1]
List without duplicates: [1, 2, 3, 4, 5]


In [93]:
def remove_duplicates(input_list):
    unique_list=[]
    for item in input_list:
        if item not in unique_list:
            unique_list.append(item)
    return unique_list
original_list=[1,1,2,3,5,6,8,8,8]
result=remove_duplicates(original_list)
print("original list is",original_list)
print("remove duplicates from list",result)
        

original list is [1, 1, 2, 3, 5, 6, 8, 8, 8]
remove duplicates from list [1, 2, 3, 5, 6, 8]


In [19]:
a=list(map(int,input().split()))
a.sort()
print(a[-2])

 1 2 2 3 4 5 6 


5


In [9]:
nested_list=[[1,2],[3,4]]
final_list=[]
for sub_list in nested_list:
    for item in sub_list:
        final_list.append(item)
print(final_list)

[1, 2, 3, 4]


In [11]:
text=input("enter a string:")
freq={}
for char in text:
    if char in freq:
        freq[char]+=1
    else:
        freq[char]=1
print(freq)

enter a string: pavan


{'p': 1, 'a': 2, 'v': 1, 'n': 1}


In [35]:
text = input("Enter a string: ")

a = {}

for char in text:
    if char in a:
        a[char] += 1
    else:
        a[char] = 1

print(a)


Enter a string:  pavan is a dancer and also a singer


{'p': 1, 'a': 7, 'v': 1, 'n': 4, ' ': 7, 'i': 2, 's': 3, 'd': 2, 'c': 1, 'e': 2, 'r': 2, 'l': 1, 'o': 1, 'g': 1}


In [13]:
dict={'name':'Alice','age':22,'grade':'A'}
dict['age']=23
dict['passed']=True
dict['age']=45
print(dict)

{'name': 'Alice', 'age': 45, 'grade': 'A', 'passed': True}


In [19]:
def merge_dicts(dict1, dict2):
    merged = dict1.copy()  
    merged.update(dict2)    
    return merged

 
d1 = {'a': 1, 'b': 2}
d2 = {'b': 3, 'c': 4}

result = merge_dicts(d1, d2)
print(result)


{'a': 1, 'b': 3, 'c': 4}


In [79]:
#strings
str="Hello world "
str2="this is a pavan"
print(str + str2)

Hello world this is a pavan


In [81]:
str="hello"
print(str)

hello


In [83]:
print(str[0])

h


In [29]:
str="hello"
print(str[-1:1])

In [87]:
print(str[1:4:2])

el


In [101]:
print(str[-3:-1])

ll


In [105]:
print(str[:3])

hel


In [107]:
print(str[3:])

lo


In [47]:
#multi line string
str1="""dammuntey pattuko ra shikavath
       pattukuntey vadiletha sindicate
       malli bujaana goddalesi 
       kooli ki potha ra adivikesi"""
a.list(str1)
print(a)

NameError: name 'a' is not defined

In [117]:
str1="Hello world"
str2="this is chitti"
str3="Hello world"
print(str1==str2)
print(str1==str3)


False
True


In [125]:
str="hello world "
for i in str:
    print(i)

h
e
l
l
o
 
w
o
r
l
d
 


In [127]:
str2="hello world"
print(len(str2))

11


In [129]:
#membership 
print('a' in 'program')
print('a'not in 'program')


True
False


In [131]:
#lists
list=["pavan","ganga","ramya","vasu"]
print(list)

['pavan', 'ganga', 'ramya', 'vasu']


In [133]:

student = ['Jack', 32, 'Computer Science', [2, 4]]
print(student)


empty_list = []
print(empty_list)

['Jack', 32, 'Computer Science', [2, 4]]
[]


In [137]:
list=["pavan","ganga","ramya","vasu"]
print(list[0])

pavan


In [139]:
print(list[-2])

ramya


In [141]:
print(list[1:4])

['ganga', 'ramya', 'vasu']


In [143]:
print(list[1:4:2])

['ganga', 'vasu']


In [145]:
print(list[:4])


['pavan', 'ganga', 'ramya', 'vasu']


In [149]:
print(list[3:])

['vasu']


In [151]:
print(list[-3])

ganga


In [159]:
list=["pavan","ganga","ramya","vasu"]
print("original list:",list)
list.append("cherry")
print("update  list:",list)

original list: ['pavan', 'ganga', 'ramya', 'vasu']
update  list: ['pavan', 'ganga', 'ramya', 'vasu', 'cherry']


In [165]:
list=["pavan","ganga","ramya","vasu"]
print(list)
list.insert(2,"mavayya")
print(list)

['pavan', 'ganga', 'ramya', 'vasu']
['pavan', 'ganga', 'mavayya', 'ramya', 'vasu']


In [169]:
numbers=[1,3,5]
print("numbers:",numbers,)
even_numbers=[2,4,6]
print("even numbers:",even_numbers)
numbers.extend(even_numbers)
print(numbers)

numbers: [1, 3, 5]
even numbers: [2, 4, 6]
[1, 3, 5, 2, 4, 6]


In [173]:
names = ['John', 'Eva', 'Laura', 'Nick', 'Jack']

# delete the item at index 1
del names[1]
print(names)

# delete items from index 1 to index 2
del names[1: 3]
print(names)

# delete the entire list
del names

# Error! List doesn't exist.
print(names)

['John', 'Laura', 'Nick', 'Jack']
['John', 'Jack']


NameError: name 'names' is not defined

In [17]:
list=[1,9,3,6,5,7,0]
list.append(6)
print(list)

[1, 9, 3, 6, 5, 7, 0, 6]


In [19]:
del list[2]
print(list)

[1, 9, 6, 5, 7, 0, 6]


In [23]:
list.sort
print(list)

[0, 1, 5, 6, 6, 7, 9]


In [27]:
print(max(list))

9


In [29]:
print(min(list))

0


In [1]:
a=(10,20,30,40,50)
b=list(a)
print(b)

[10, 20, 30, 40, 50]


In [5]:
 b[1]=99
print(b)

[10, 99, 99, 40, 50]


In [11]:
a=tuple(b)
print(a)

(10, 99, 99, 40, 50)


In [13]:
dict={'pavan':45,'narendra':55,'nani':44,'bahdoor':67}
print(dict)

{'pavan': 45, 'narendra': 55, 'nani': 44, 'bahdoor': 67}


In [15]:
dict['veerareddy']=66
print(dict)

{'pavan': 45, 'narendra': 55, 'nani': 44, 'bahdoor': 67, 'veerareddy': 66}


In [17]:
dict['narendra']=78
print(dict)

{'pavan': 45, 'narendra': 78, 'nani': 44, 'bahdoor': 67, 'veerareddy': 66}


In [19]:
del dict['pavan']
print(dict)

{'narendra': 78, 'nani': 44, 'bahdoor': 67, 'veerareddy': 66}


In [33]:
print("keys in dict:")
for i in dict.keys():
    print(i)

keys in dict:
narendra
nani
bahdoor
veerareddy


In [31]:
print("values in dict:")
for j in dict.values():
    print(j)

values in dict:
78
44
67
66


In [39]:
str="pavan"
for i in str:
    print(i)

p
a
v
a
n


In [53]:
list=["narendra","pavan","narendra","bahdoor","hari"]
list[2]='veera'
print(list)

['narendra', 'pavan', 'veera', 'bahdoor', 'hari']


In [11]:
def add_ing_ly(str):
    if len(str) <3:
        return str
    elif str.endswith("ing"):
        return str +"ly"
    else:
        return str+ "ing"
word=add_ing_ly('pa')
print(word)


pa


In [13]:
def add_ing_ly(word):
    if len(word)<3:
        return word
    elif word.endswith("ing"):
        return word+"ly"
    else:
        return word+"ing"
result=add_ing_ly("swimming")
print(result)

swimmingly


In [36]:
def copy_price_dict(item_price_dict):
    return dict(item_price_dict)  # or item_price_dict.copy()
original_dict = {'apple': 10, 'banana': 5}
new_dict = copy_price_dict(original_dict)
print(original_dict)  # Still {'apple': 10, 'banana': 5}
print(new_dict) # Now {'apple': 10, 'banana': 7}


{'apple': 10, 'banana': 5}
{'apple': 10, 'banana': 5}


In [48]:
 
given_dict={'ACME':45.23,'AAPL':612.78,'IBM':205.55,'HPQ':37.20,'FB':10.75}
new_dict=dict(given_dict)
print("given dictionary:",given_dict)
print("new dictionary:",new_dict)

given dictionary: {'ACME': 45.23, 'AAPL': 612.78, 'IBM': 205.55, 'HPQ': 37.2, 'FB': 10.75}
new dictionary: {'ACME': 45.23, 'AAPL': 612.78, 'IBM': 205.55, 'HPQ': 37.2, 'FB': 10.75}


In [69]:
def expensive(prices_dict):
    return{item:price for item,price in prices_dict.items() if price>200}
        
prices_dict={'ACME':45.23,'AAPL':612.78,'IBM':205.55,'HPQ':37.20,'FB':10.75}
result=expensive(prices_dict)
print(result)

{'AAPL': 612.78, 'IBM': 205.55}


In [192]:
def expensive(prices_dict):
    abd={}
    for item,price in  prices_dict.items():
        if price>200:
            abd[item]=price
    
    return abd 

prices_dict={'ACME':45.23,'AAPL':612.78,'IBM':205.55,'HPQ':37.20,'FB':10.75}
result=expensive(prices_dict)
print(result)
            
     

{'AAPL': 612.78, 'IBM': 205.55}


In [65]:
a=(1,2,3)
x,y,z=a
print(x,y,z)

1 2 3


In [69]:
a=[[1,2],[3,4]]
my_list=[]
for sublist in a:
    for item in sublist:
        my_list.append(item)
print(my_list)

[1, 2, 3, 4]


In [97]:
dict1={"name":"pavan","age":22}
dict2={"name":"narendra","age":21}
add= dict1 | dict2
print(add)

{'name': 'narendra', 'age': 21}


In [105]:
text = "helloworld"
print("h:", text.count('h'))
print("e:", text.count('e'))
print("l:", text.count('l'))
print("0:",text.count('0'))
print("w:",text.count('w'))
print("r:",text.count('r'))
print("d:",text.count('d'))


h: 1
e: 1
l: 3
0: 0
w: 1
r: 1
d: 1


In [49]:
from collections import Counter
a=Counter("hello")
print(a)

Counter({'l': 2, 'h': 1, 'e': 1, 'o': 1})


In [53]:
#string methods
#upper
text="pavan"
print(text.upper())

PAVAN


In [17]:
text="PAVAN"
print(text.lower())
print(text.capitalize())

pavan
Pavan


In [19]:
text="  pavan "
print(text.strip())

pavan


In [25]:
text ="pavan"
print(text.find("a"))

1


In [63]:
value=11
value=43
print(value)

43


In [61]:
value=11
value=43
print(value)

43


In [21]:
import re
pattern = "12345"
text = "My phone number is 12345"
match = re.search(pattern,text)
match



<re.Match object; span=(19, 24), match='12345'>

In [75]:
import re
 
text="i am a begginer to this and this begginer is level"
pattern="begginer"
match= re.search(pattern,text)
match

<re.Match object; span=(7, 15), match='begginer'>

In [77]:
match.group()

'begginer'

In [79]:
print(match.group(1))

IndexError: no such group

In [81]:
match.end()

15

In [83]:
match=re.findall(pattern,text)
match

['begginer', 'begginer']

In [85]:
len(match)

2

In [212]:
import re
text="my telephone number is 970-449-7012 and also 994-9112-2282 and 9999-34334-8884 and 994-911-2158"
pattern=re.compile(r'\d{3}-\d{4}-\d{4}')
match=pattern.search(text)
match
#match=re.search(pattern,text)
#pattern
#pattern.span()
#pattern.start()
#pattern.end()
#match=re.search(pattern,text)
#match

<re.Match object; span=(45, 58), match='994-9112-2282'>

In [87]:
match.group()


AttributeError: 'list' object has no attribute 'group'

In [89]:

print(match.group(1))

AttributeError: 'list' object has no attribute 'group'

In [95]:

import re

text = "my telephone number is 970-449-7012 and also 994-9112-2282 and 9999-34334-8884 and 994-911-2158"
pattern = re.compile(r'(\d{3})-(\d{4})-(\d{4})')
match = pattern.search(text)

print(match.group())    # ➝ '970-449-7012'
print(match.group(1))   # ➝ '970'
print(match.group(2))   # ➝ '449'
print(match.group(3))   # ➝ '7012'


994-9112-2282
994
9112
2282


In [97]:
print(match.group(2))

9112


In [99]:
text=re.search(r'man|women',"this man is here")
text

<re.Match object; span=(5, 8), match='man'>

In [101]:
text=re.findall(r'man|women',"this man is a good man")
text

['man', 'man']

In [250]:
text=re.findall(r'.at',"the cat sat on hat")
text

['cat', 'sat', 'hat']

In [294]:
text=re.search(r'.at',"the cat sat on hat")
text

<re.Match object; span=(4, 7), match='cat'>

In [296]:
text=re.findall(r'\Sat',"the cat sat on hat")
text

['cat', 'sat', 'hat']

In [298]:
text=re.findall(r'\d$'," 4556")
text

['6']

In [300]:
import re
text=re.search(r'\d$',"34344")
text

<re.Match object; span=(4, 5), match='4'>

In [103]:
text=re.findall(r'^\d',"  1and 232")
text

[]

In [344]:
import re
text=re.search(r'[^\d]',"2 and 3 is sum of 5")
text


<re.Match object; span=(1, 2), match=' '>

In [346]:
text.group()

' '

In [358]:
text=' '.join(re.findall(r'[^\d]+',"5 is sum of 2 and 3"))
text

' is sum of   and '

In [356]:
text=re.findall(r'[^\d]+',"5 is sum of 2 and 3")
text

[' is sum of ', ' and ']

In [ ]:
contacts = {
    "John": {"phone": "1234567890", "email": "john@example.com"},
    "Alice": {"phone": "9876543210", "email": "alice@example.com"}
}
import os

FILENAME = "contacts.txt"

def load_contacts():
    if os.path.exists(FILENAME):
        with open(FILENAME, "r") as f:
            return eval(f.read())  # or use json.loads if using JSON format
    return {}

def save_contacts(contacts):
    with open(FILENAME, "w") as f:
        f.write(str(contacts))

def add_contact(contacts):
    name = input("Enter name: ")
    if name in contacts:
        print("Contact already exists.")
        return
    phone = input("Enter phone number: ")
    email = input("Enter email: ")
    contacts[name] = {"phone": phone, "email": email}
    print("Contact added.")

def view_contacts(contacts):
    if not contacts:
        print("No contacts found.")
        return
    for name, info in contacts.items():
        print(f"\nName: {name}")
        print(f"Phone: {info['phone']}")
        print(f"Email: {info['email']}")

def search_contact(contacts):
    name = input("Enter name to search: ")
    if name in contacts:
        print(f"Phone: {contacts[name]['phone']}")
        print(f"Email: {contacts[name]['email']}")
    else:
        print("Contact not found.")

def delete_contact(contacts):
    name = input("Enter name to delete: ")
    if name in contacts:
        del contacts[name]
        print("Contact deleted.")
    else:
        print("Contact not found.")

def main():
    contacts = load_contacts()
    while True:
        print("\n=== Contact Book ===")
        print("1. Add Contact")
        print("2. View Contacts")
        print("3. Search Contact")
        print("4. Delete Contact")
        print("5. Save & Exit")

        choice = input("Choose an option: ")

        if choice == "1":
            add_contact(contacts)
        elif choice == "2":
            view_contacts(contacts)
        elif choice == "3":
            search_contact(contacts)
        elif choice == "4":
            delete_contact(contacts)
        elif choice == "5":
            save_contacts(contacts)
            print("Contacts saved. Exiting...")
            break
        else:
            print("Invalid choice. Try again.")

if __name__ == "__main__":
    main()


In [1]:
import os 
os.system("shutdown  0")

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\pavan\AppData\Local\Temp\ipykernel_23948\1851423169.py:2: SyntaxWarning: invalid escape sequence '\s'
  os.system("shutdown \s \t 0")


1

In [3]:
import pandas as pd

In [5]:
d=pd.read_csv(r"C:\Users\pavan\Downloads\Titanic-Dataset1.csv")
df=pd.DataFrame(d)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [7]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [9]:
df.head(10)




PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [11]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [13]:
df.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [15]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [17]:
df.shape

(891, 12)

In [19]:
df[0:10:1]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [21]:
df[0:10:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
2            3         1       3   
4            5         0       3   
6            7         0       1   
8            9         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
4                           Allen, Mr. William Henry    male  35.0      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
2      0  STON/O2. 3101282   7.9250   NaN        S  
4      0            373450   8.0500   NaN        S  
6      0             17463  51.8625   E46        S  
8      2            347742  11.1333   NaN        S

In [23]:
df["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [25]:
df[["Survived","Pclass"]]

Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]

In [27]:
df[["Survived","Pclass"]][0:10:2]

Survived  Pclass
0         0       3
2         1       3
4         0       3
6         0       1
8         1       3

In [29]:
#for rec in df.iterrows():
    print(rec)

IndentationError: unexpected indent (3917773464.py, line 2)

In [277]:
df.iloc[0:1]

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [39]:
df.loc[2,["Survived"]]

Survived    1
Name: 2, dtype: object

In [71]:
df.loc[2,["Survived","Pclass"]]

Survived    1
Pclass      3
Name: 2, dtype: object

In [73]:
df.loc[0:5]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

In [75]:
df.iloc[0:5]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [77]:
df.loc[0:5,"Pclass"]

0    3
1    1
2    3
3    1
4    3
5    3
Name: Pclass, dtype: int64

In [41]:
df.loc[0:6,"Name":"Embarked"]

Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S

In [45]:
df.iloc[0:5]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [49]:
df.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [55]:
df.iloc[1:5]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [87]:
df.iloc[4,4]

'male'

In [57]:
df.iloc[0:5,0:3]

PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [91]:
df.iloc[0:5,1]

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [65]:
df.loc[[1,5,3]]

PassengerId  Survived  Pclass  \
1            2         1       1   
5            6         0       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
5                                   Moran, Mr. James    male   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch    Ticket     Fare Cabin Embarked  
1      0  PC 17599  71.2833   C85        C  
5      0    330877   8.4583   NaN        Q  
3      0    113803  53.1000  C123        S

In [129]:
df.iloc[[1,5,8,9]]

PassengerId  Survived  Pclass  \
1            2         1       1   
5            6         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
5                                   Moran, Mr. James    male   NaN      0   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch    Ticket     Fare Cabin Embarked  Total  
1      0  PC 17599  71.2833   C85        C      2  
5      0    330877   8.4583   NaN        Q      3  
8      2    347742  11.1333   NaN        S      4  
9      0    237736  30.0708   NaN        C      3

In [67]:
df.iloc[:,[1]]

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [69]:
df.iloc[0:7,[1,2,3]]

Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry
5         0       3                                   Moran, Mr. James
6         0       1                            McCarthy, Mr. Timothy J

In [101]:
df.sort_values("Pclass")

PassengerId  Survived  Pclass  \
445          446         1       1   
310          311         1       1   
309          310         1       1   
307          308         1       1   
306          307         1       1   
..           ...       ...     ...   
379          380         0       3   
381          382         1       3   
382          383         0       3   
371          372         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
445                          Dodge, Master. Washington    male   4.0      0   
310                     Hays, Miss. Margaret Bechstein  female  24.0      0   
309                     Francatelli, Miss. Laura Mabel  female  30.0      0   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1   
306                            Fleming, Miss. Margaret  female   NaN      0   
..                                                 ...     ...   ...    ...   
379                        Gustafsson, Mr. Karl Gideon    male  19.0      0   
381                        Nakid, Miss. Maria ("Mary")  female   1.0      0   
382                                 Tikkanen, Mr. Juho    male  32.0      0   
371                          Wiklund, Mr. Jakob Alfred    male  18.0      1   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch             Ticket      Fare Cabin Embarked  
445      2              33638   81.8583   A34        S  
310      0              11767   83.1583   C54        C  
309      0           PC 17485   56.9292   E36        C  
307      0           PC 17758  108.9000   C65        C  
306      0              17421  110.8833   NaN        C  
..     ...                ...       ...   ...      ...  
379      0             347069    7.7750   NaN        S  
381      2               2653   15.7417   NaN        C  
382      0  STON/O 2. 3101293    7.9250   NaN        S  
371      0            3101267    6.4958   NaN        S  
890      0             370376    7.7500   NaN        Q  

[891 rows x 12 columns]

In [103]:
df.sort_values("Pclass",ascending=False)

PassengerId  Survived  Pclass  \
0              1         0       3   
511          512         0       3   
500          501         0       3   
501          502         0       3   
502          503         0       3   
..           ...       ...     ...   
102          103         0       1   
710          711         1       1   
711          712         0       1   
712          713         1       1   
445          446         1       1   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
511                                 Webber, Mr. James    male   NaN      0   
500                                  Calic, Mr. Petar    male  17.0      0   
501                               Canavan, Miss. Mary  female  21.0      0   
502                    O'Sullivan, Miss. Bridget Mary  female   NaN      0   
..                                                ...     ...   ...    ...   
102                         White, Mr. Richard Frasar    male  21.0      0   
710  Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")  female  24.0      0   
711                                Klaber, Mr. Herman    male   NaN      0   
712                          Taylor, Mr. Elmer Zebley    male  48.0      1   
445                         Dodge, Master. Washington    male   4.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
511      0  SOTON/OQ 3101316   8.0500   NaN        S  
500      0            315086   8.6625   NaN        S  
501      0            364846   7.7500   NaN        Q  
502      0            330909   7.6292   NaN        Q  
..     ...               ...      ...   ...      ...  
102      1             35281  77.2875   D26        S  
710      0          PC 17482  49.5042   C90        C  
711      0            113028  26.5500  C124        S  
712      0             19996  52.0000  C126        S  
445      2             33638  81.8583   A34        S  

[891 rows x 12 columns]

In [71]:
df.sort_values(["Survived","Name"])

PassengerId  Survived  Pclass  \
845          846         0       3   
746          747         0       3   
308          309         0       2   
365          366         0       3   
401          402         0       3   
..           ...       ...     ...   
55            56         1       1   
830          831         1       3   
325          326         1       1   
559          560         1       3   
286          287         1       3   

                                             Name     Sex   Age  SibSp  Parch  \
845                           Abbing, Mr. Anthony    male  42.0      0      0   
746                   Abbott, Mr. Rossmore Edward    male  16.0      1      1   
308                           Abelson, Mr. Samuel    male  30.0      1      0   
365                Adahl, Mr. Mauritz Nils Martin    male  30.0      0      0   
401                               Adams, Mr. John    male  26.0      0      0   
..                                            ...     ...   ...    ...    ...   
55                              Woolner, Mr. Hugh    male   NaN      0      0   
830       Yasbeck, Mrs. Antoni (Selini Alexander)  female  15.0      1      0   
325                      Young, Miss. Marie Grice  female  36.0      0      0   
559  de Messemaeker, Mrs. Guillaume Joseph (Emma)  female  36.0      1      0   
286                       de Mulder, Mr. Theodore    male  30.0      0      0   

        Ticket      Fare Cabin Embarked  
845  C.A. 5547    7.5500   NaN        S  
746  C.A. 2673   20.2500   NaN        S  
308  P/PP 3381   24.0000   NaN        C  
365     C 7076    7.2500   NaN        S  
401     341826    8.0500   NaN        S  
..         ...       ...   ...      ...  
55       19947   35.5000   C52        S  
830       2659   14.4542   NaN        C  
325   PC 17760  135.6333   C32        C  
559     345572   17.4000   NaN        S  
286     345774    9.5000   NaN        S  

[891 rows x 12 columns]

In [107]:
df["Total"]=0
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Total  
0        0         A/5 21171   7.2500   NaN        S      0  
1        0          PC 17599  71.2833   C85        C      0  
2        0  STON/O2. 3101282   7.9250   NaN        S      0  
3        0            113803  53.1000  C123        S      0  
4        0            373450   8.0500   NaN        S      0  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      0  
887      0            112053  30.0000   B42        S      0  
888      2        W./C. 6607  23.4500   NaN        S      0  
889      0            111369  30.0000  C148        C      0  
890      0            370376   7.7500   NaN        Q      0  

[891 rows x 13 columns]

In [109]:
df["Total"]=df["Survived"]+df["Pclass"]
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Total  
0        0         A/5 21171   7.2500   NaN        S      3  
1        0          PC 17599  71.2833   C85        C      2  
2        0  STON/O2. 3101282   7.9250   NaN        S      4  
3        0            113803  53.1000  C123        S      2  
4        0            373450   8.0500   NaN        S      3  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      2  
887      0            112053  30.0000   B42        S      2  
888      2        W./C. 6607  23.4500   NaN        S      3  
889      0            111369  30.0000  C148        C      2  
890      0            370376   7.7500   NaN        Q      3  

[891 rows x 13 columns]

In [111]:
df.drop(columns="Name")

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0              1         0       3    male  22.0      1      0   
1              2         1       1  female  38.0      1      0   
2              3         1       3  female  26.0      0      0   
3              4         1       1  female  35.0      1      0   
4              5         0       3    male  35.0      0      0   
..           ...       ...     ...     ...   ...    ...    ...   
886          887         0       2    male  27.0      0      0   
887          888         1       1  female  19.0      0      0   
888          889         0       3  female   NaN      1      2   
889          890         1       1    male  26.0      0      0   
890          891         0       3    male  32.0      0      0   

               Ticket     Fare Cabin Embarked  Total  
0           A/5 21171   7.2500   NaN        S      3  
1            PC 17599  71.2833   C85        C      2  
2    STON/O2. 3101282   7.9250   NaN        S      4  
3              113803  53.1000  C123        S      2  
4              373450   8.0500   NaN        S      3  
..                ...      ...   ...      ...    ...  
886            211536  13.0000   NaN        S      2  
887            112053  30.0000   B42        S      2  
888        W./C. 6607  23.4500   NaN        S      3  
889            111369  30.0000  C148        C      2  
890            370376   7.7500   NaN        Q      3  

[891 rows x 12 columns]

In [113]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [115]:
df.drop_duplicates()

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Total  
0        0         A/5 21171   7.2500   NaN        S      3  
1        0          PC 17599  71.2833   C85        C      2  
2        0  STON/O2. 3101282   7.9250   NaN        S      4  
3        0            113803  53.1000  C123        S      2  
4        0            373450   8.0500   NaN        S      3  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      2  
887      0            112053  30.0000   B42        S      2  
888      2        W./C. 6607  23.4500   NaN        S      3  
889      0            111369  30.0000  C148        C      2  
890      0            370376   7.7500   NaN        Q      3  

[891 rows x 13 columns]

In [117]:
df.fillna(80)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  80.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Total  
0        0         A/5 21171   7.2500    80        S      3  
1        0          PC 17599  71.2833   C85        C      2  
2        0  STON/O2. 3101282   7.9250    80        S      4  
3        0            113803  53.1000  C123        S      2  
4        0            373450   8.0500    80        S      3  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000    80        S      2  
887      0            112053  30.0000   B42        S      2  
888      2        W./C. 6607  23.4500    80        S      3  
889      0            111369  30.0000  C148        C      2  
890      0            370376   7.7500    80        Q      3  

[891 rows x 13 columns]

In [119]:
df.loc[df["Pclass"]<10]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Total  
0        0         A/5 21171   7.2500   NaN        S      3  
1        0          PC 17599  71.2833   C85        C      2  
2        0  STON/O2. 3101282   7.9250   NaN        S      4  
3        0            113803  53.1000  C123        S      2  
4        0            373450   8.0500   NaN        S      3  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      2  
887      0            112053  30.0000   B42        S      2  
888      2        W./C. 6607  23.4500   NaN        S      3  
889      0            111369  30.0000  C148        C      2  
890      0            370376   7.7500   NaN        Q      3  

[891 rows x 13 columns]

In [131]:
df.loc[(df["Pclass"]<10) & (df["Survived"]<10)]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Total  
0        0         A/5 21171   7.2500   NaN        S      3  
1        0          PC 17599  71.2833   C85        C      2  
2        0  STON/O2. 3101282   7.9250   NaN        S      4  
3        0            113803  53.1000  C123        S      2  
4        0            373450   8.0500   NaN        S      3  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      2  
887      0            112053  30.0000   B42        S      2  
888      2        W./C. 6607  23.4500   NaN        S      3  
889      0            111369  30.0000  C148        C      2  
890      0            370376   7.7500   NaN        Q      3  

[891 rows x 13 columns]

In [85]:
df.loc[df["Name"].str.contains("z")]

PassengerId  Survived  Pclass  \
11            12         1       1   
53            54         1       2   
66            67         1       2   
69            70         0       3   
79            80         1       3   
130          131         0       3   
133          134         1       2   
152          153         0       3   
161          162         1       2   
177          178         0       1   
218          219         1       1   
255          256         1       3   
272          273         1       2   
307          308         1       1   
337          338         1       1   
341          342         1       1   
354          355         0       3   
365          366         0       3   
430          431         1       1   
454          455         0       3   
496          497         1       1   
513          514         1       1   
533          534         1       3   
541          542         0       3   
586          587         0       2   
588          589         0       3   
609          610         1       1   
642          643         0       3   
670          671         1       2   
679          680         1       1   
715          716         0       3   
721          722         0       3   
742          743         1       1   
774          775         1       2   
859          860         0       3   
874          875         1       2   
886          887         0       2   

                                                  Name     Sex   Age  SibSp  \
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1   
66                        Nye, Mrs. (Elizabeth Ramell)  female  29.0      0   
69                                   Kink, Mr. Vincenz    male  26.0      2   
79                            Dowdell, Miss. Elizabeth  female  30.0      0   
130                               Drazenoic, Mr. Jozef    male  33.0      0   
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
161  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...  female  40.0      0   
177                         Isham, Miss. Ann Elizabeth  female  50.0      0   
218                              Bazzani, Miss. Albina  female  32.0      0   
255            Touma, Mrs. Darwis (Hanne Youssef Razi)  female  29.0      0   
272          Mellinger, Mrs. (Elizabeth Anne Maidment)  female  41.0      0   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1   
337                    Burns, Miss. Elizabeth Margaret  female  41.0      0   
341                     Fortune, Miss. Alice Elizabeth  female  24.0      3   
354                                  Yousif, Mr. Wazli    male   NaN      0   
365                     Adahl, Mr. Mauritz Nils Martin    male  30.0      0   
430          Bjornstrom-Steffansson, Mr. Mauritz Hakan    male  28.0      0   
454                                Peduzzi, Mr. Joseph    male   NaN      0   
496                     Eustis, Miss. Elizabeth Mussey  female  54.0      1   
513     Rothschild, Mrs. Martin (Elizabeth L. Barrett)  female  54.0      1   
533             Peter, Mrs. Catherine (Catherine Rizk)  female   NaN      0   
541               Andersson, Miss. Ingeborg Constanzia  female   9.0      4   
586                            Jarvis, Mr. John Denzil    male  47.0      0   
588                              Gilinski, Mr. Eliezer    male  22.0      0   
609                          Shutes, Miss. Elizabeth W  female  40.0      0   
642                      Skoog, Miss. Margit Elizabeth  female   2.0      3   
670  Brown, Mrs. Thomas William Solomon (Elizabeth ...  female  40.0      1   
679                 Cardeza, Mr. Thomas Drake Martinez    male  36.0      0   
715         Soholt, Mr. Peter Andreas Lauritz Andersen    male  19.0      0   
721                          Jen

In [79]:
df[0:1]

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [87]:
#numpy
import numpy as np

In [89]:
a=np.array(1)
print(a)

1


In [91]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [93]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
a[1][0][1]


8

In [101]:
a=np.asarray([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
a=np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
a=np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [111]:
a=np.full([2,3],7)
a

array([[7, 7, 7],
       [7, 7, 7]])

In [113]:
a=np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [115]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
a=np.arange(10,110,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [127]:
a.reshape([5,2])


array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [141]:
a=np.linspace(10,100,4,endpoint=False,retstep=True)
a

(array([10. , 32.5, 55. , 77.5]), 22.5)

In [151]:
a=np.logspace(10,100,10,base=2)
a

array([1.02400000e+03, 1.04857600e+06, 1.07374182e+09, 1.09951163e+12,
       1.12589991e+15, 1.15292150e+18, 1.18059162e+21, 1.20892582e+24,
       1.23794004e+27, 1.26765060e+30])

In [153]:
a=np.logspace(1,10,10,base=2)
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [155]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
np.size(a)

6

In [163]:
a.dtype

dtype('int32')

In [165]:
a.shape

(2, 3)

In [167]:
a.ndim

2

In [169]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [171]:
b=np.copy(a)
b

array([1, 2, 3, 4, 5])

In [175]:
c=b.view()
c

array([1, 2, 3, 4, 5])

In [179]:
a=np.array([1,2,3,4,5,6])
b=np.array([[4,5,6],[7,8,9]])
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

In [181]:
np.insert(a,3,10)

array([ 1,  2,  3, 10,  4,  5,  6])

In [185]:
np.delete(a,3)

array([1, 2, 3, 5, 6])

In [193]:
a=np.array([1,2,3,4,5])
b=np.array([7,8,9,0,1])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 7, 8, 9, 0, 1])

In [195]:
np.stack((a,b))

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 0, 1]])

In [199]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 0, 1]])

In [203]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 0, 1]])

In [205]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 7, 8, 9, 0, 1])

In [207]:
np.dstack((a,b))

array([[[1, 7],
        [2, 8],
        [3, 9],
        [4, 0],
        [5, 1]]])

In [209]:
a=np.array([6,1,4,2,0,3,8])
np.sort(a)

array([0, 1, 2, 3, 4, 6, 8])

In [213]:
np.where([4])

(array([0], dtype=int64),)

In [221]:
np.searchsorted(a,2)

2

In [229]:
a=np.array([1,2,3,4,5,4,8,9,1,2])
np.split(a,5)

[array([1, 2]), array([3, 4]), array([5, 4]), array([8, 9]), array([1, 2])]

In [233]:
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
np.add(a,b)

array([ 2,  4,  6,  8, 10, 12])

In [235]:
np.subtract(a,b)

array([0, 0, 0, 0, 0, 0])

In [237]:
np.multiply(a,b)

array([ 1,  4,  9, 16, 25, 36])

In [239]:
np.divide(a,b)

array([1., 1., 1., 1., 1., 1.])

In [253]:
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [255]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [257]:
np.sum(a)

21

In [259]:
np.max(a)

6

In [261]:
np.min(a)

1

In [263]:
np.std(a)

1.707825127659933

In [265]:
np.var(a)

2.9166666666666665

In [267]:
np.mean(a)

3.5

In [269]:
np.median(a)

3.5

AttributeError: module 'numpy' has no attribute 'flatten'

In [1]:
import pandas as pd

In [22]:
data={"pavan":[1,2,3,4],
      "ganesh":[6,7,8,9]}
df=pd.DataFrame(data)
df

pavan  ganesh
0      1       6
1      2       7
2      3       8
3      4       9

In [24]:
data1={"pavan":[0,7],
       "ganesh":[9,7]}
df1=pd.DataFrame(data1)
df1

pavan  ganesh
0      0       9
1      7       7

In [30]:
df2=df.append([df1],ignore_index=True)
df2

AttributeError: 'DataFrame' object has no attribute 'append'